[project]
name = "{{ cookiecutter.package_name }}"
version = "0.0.1"
description = "{{ cookiecutter.description }}"
authors = [
    { name = "{{ cookiecutter.author }}", email = "{{ cookiecutter.author_email }}" }
]
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
{%- if cookiecutter.executor == "Threadpool" %}
    "orchestrator-core"
{%- elif cookiecutter.executor == "Celery" %}
    "orchestrator-core[celery]"
{%- endif %}
]

[dependency-groups]
dev = [
    "faker>=40.32.0",
    "mypy>=2.3,<2.4",
    "pre-commit-uv>=4.3.0",
    "pytest>=9.1.1",
    "ruff>=0.15.22",
    "urllib3_mock>=0.3.3",
]

[build-system]
requires = ["uv_build==0.11.29"]
build-backend = "uv_build"

[tool.uv]
prerelease = "if-necessary"

[tool.uv.build-backend]
module-name = "{{ cookiecutter.project_slug }}"
module-root = ""

[tool.ruff]
extend-exclude = [
    "htmlcov",
    "{{ cookiecutter.project_slug }}/migrations",
    "docs",
]
target-version = "py313"
line-length = 120

[tool.ruff.lint]
ignore = [
    "B901",
    "C901",
    "COM812",
    "D203",
    "D213",
    "ISC001",
    "N805",
    "PLC2801",
    "PLR0913",
    "PLR0904",
    "PLW1514",
    "FURB118",
    "S311",
]
select = [
    "A",
    "ARG",
    "B",
    "BLE",
    "C",
    "COM",
    "C4",
    "C90",
    "D",
    "DTZ",
    "E",
    "EM",
    "ERA",
    "F",
    "FA",
    "FBT",
    "FLY",
    "FURB",
    "G",
    "I",
    "ICN",
    "INP",
    "ISC",
    "LOG",
    "N",
    "PERF",
    "PGH",
    "PIE",
    "PL",
    "PT",
    "PTH",
    "PYI",
    "Q",
    "RET",
    "R",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "SLF",
    "T",
    "T20",
    "TID",
    "TRY",
    "UP",
    "W",
    "YTT"
]

[tool.ruff.lint.mccabe]
max-complexity = 15

[tool.ruff.lint.pylint]
max-branches = 15

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.per-file-ignores]
"{{ cookiecutter.project_slug }}/__init__.py" = ["ERA001"]
"{{ cookiecutter.project_slug }}/products/__init__.py" = ["ERA001"]
"{{ cookiecutter.project_slug }}/workflows/*" = ["FBT001", "PLR0917", "PLR0914", "ERA001"]
"test/**" = ["ARG001", "D", "S101", "PLR2004", "PLR0917", "PLR0914", "PLC0415", "PLC2701", "PGH003"]
"test/fixtures/__init__.py" = ["ERA001"]

[tool.ruff.lint.isort]
known-third-party = ["pydantic", "migrations"]
known-first-party = ["test", "docs"]

[tool.mypy]
exclude = "({{ cookiecutter.project_slug }}/migrations|htmlcov)"
ignore_missing_imports = true
disallow_untyped_defs = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unreachable = true
strict_equality = true
show_error_codes = true
show_column_numbers = true
explicit_package_bases = true
plugins = ["pydantic.mypy"]
disable_error_code = "annotation-unchecked"

[[tool.mypy.overrides]]
module = "test.*"
disallow_untyped_calls = false
disallow_untyped_defs = false
disallow_incomplete_defs = false

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true

[tool.pytest.ini_options]
markers = ["noautofixt"]
filterwarnings = ["ignore", "default:::{{ cookiecutter.project_slug }}"]
asyncio_default_fixture_loop_scope = "function"
testpaths = ["test"]

[tool.pytest_env]
TRANSLATIONS_DIR = "{{ cookiecutter.project_slug }}/translations"

[tool.coverage.run]
branch = true
fail_under = 90
omit = ["{{ cookiecutter.project_slug }}/migrations/*"]
